// Generated by CoffeeScript 1.10.0
(function() {
  var assert, expect;

  assert = chai.assert;

  expect = chai.expect;

  describe('Game', function() {
    var deck, game, hand;
    game = null;
    deck = null;
    hand = null;
    beforeEach(function() {
      return game = new Game();
    });
    describe('Decks', function() {
      return it('should have a deck', function() {
        return assert(game.get('deck'));
      });
    });
    describe('Hands', function() {
      it('should have a player hand', function() {
        return assert(game.get('playerHand'));
      });
      return it('should have a dealer hand', function() {
        return assert(game.get('dealerHand'));
      });
    });
    return describe('Game Logic', function() {
      return it('should call checkForBusts on card draw', function() {
        var spy;
        spy = chai.spy(game.checkForBusts);
        game.checkForBusts = spy;
        game.get('playerHand').hit();
        return expect(spy).to.have.been.called();
      });
    });
  });

}).call(this);

//# sourceMappingURL=GameSpec.js.map
